"""changes done in Active access token model

Revision ID: 8f04acdd0a0a
Revises: 164409804184
Create Date: 2025-03-04 13:17:54.571397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f04acdd0a0a'
down_revision = '164409804184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_access_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('active_access_tokens_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_access_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('active_access_tokens_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
